//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnagramSolver.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnagramSolver.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000-as	sktv	1000-ajam	1
        ///1000-is	sktv	1000-iui	5
        ///100-as	sktv	100-Ä…sias	2
        ///100-as	sktv	100-osios	1
        ///100-as	sktv	100-Å³jÅ³	2
        ///100-metis	dkt	100-metis	1
        ///100-tas	sktv	100-Å³jÅ³	1
        ///10-as	sktv	10-as	1
        ///10-as	sktv	10-Ä…jÄ…	1
        ///10-as	sktv	10-o	1
        ///10-as	sktv	10-oji	1
        ///10-as	sktv	10-ojo	1
        ///10-as	sktv	10-osios	1
        ///10-tas	sktv	10-tas	7
        ///10-tis	sktv	10-ties	2
        ///110-tis	sktv	110-Äiai	1
        ///11-12-a	sktv	11-12-os	1
        ///11-a	sktv	11-os	1
        ///11-as	sktv	11-Ä…jÄ…	2
        ///11-as	sktv	11-oji	3
        ///11-as	sktv	11-osios	5
        ///120-as	sktv	120-osioms	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string zodynas {
            get {
                return ResourceManager.GetString("zodynas", resourceCulture);
            }
        }
    }
}
